### PR TITLE
Fixed the form elements varying height bug

### LINKED ISSUE #22: [Cub] Height of form elements vary
**Describe the bug**  
The height of the elements in the form is not fixed. When the height of the viewport is decreased (due to opening of a keyboard on mobile phones) their height decrease.

**To Reproduce**
Steps to reproduce the behavior :  
1. Open Cub's Contraption on a mobile device
2. Tap on "Enter episode number"
3. Your keyboard will open and you can see that height of all form elements has changed.

**Expected behavior**  
The height of the elements should be the same.

**Screenshots**  
Before:  
Before opening keyboard
After:  
After opening keyboard

### PR DESCRIPTION
**Pull request by Sashankr**
Hey,

I fixed the issue #22  please review it and merge it into the master branch.
I found out that there was an issue with the height property for mobile screens.
I just changed two lines of code, I added height: max-content property for 480px and 360px media queries
Hope this helps out your website.

Thanks in advance!

input fields fixed

Fixes #22

### CODE REVIEW

**Review by mmaismma — APPROVED** [review]
Very nice. Although I would like to mention that, in [the beta version](https://github.com/Hermit-Tools/Thumbnail-Maker/tree/master/Source/cubfan135) we changed the layout to `grid`. The new layout fixed this issue but we did not close it as we did not release the beta version. Next time you contribute, commit all changes in the beta version (which is located in *Source*). I will also make sure to mention if an issue is fixed in the beta version.

Your work was clever and nice, why don't you try fixing #23? I am sure you can.

**Comment by Sashankr** [comment]
Thanks a lot! I will contribute to your project whenever I can! Happy that it helped you :)

**Comment by Sashankr** [comment]
Adding thank you comment

**Comment by mmaismma** [comment]
Very pleased with your generosity. I would like to mention that further inspections have reopened this issue (#22). I have added more information and assigned the issue to you. Happy coding! :)

**Pull request merged**
