### PR TITLE
Fixed #27 making the label element receive focus

### LINKED ISSUE #27: [Cub] Choose background cannot be focused with keyboard
**Description**
The *Choose Background* button can not be focused on by the keyboard. This is because the button is not an `input` nor `button` or anything stated *interactive* in the accessibility tree, it is rather a `label` and it's corresponding `input` is hidden by CSS.

**Possible solution(s)**
One possible solution is to add the attribute [`tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) to the `label` with value `0`.

### PR DESCRIPTION
**Pull request by moody2times**
Issue: The label "Choose Background" was not focusable.

Resolution: I studied the reason the label was not focusable even with adding the attribute tabindex=0. I discovered from my research that it was because label elements have a default behaviour of passing the focus to the input element they label. So, my solution was to prevent that default behaviour using javascript. After preventing the default behaviour I added tabindex attribute and the label received focus without passing it on.
At this point, I have solved this issue you opened. However, the element still had other keyboard accessibility problems. For example, it did not have interactive semantics. For that I changed the role of the element to button using the role attribute. There was finally, the problem of interactivity. So, again I used javascript to add interactivity by adding the keyboard keydown event to the label element so that it can call the click method on the input button.

### CODE REVIEW

**Review by mmaismma — APPROVED** [review]
Nicely done; thank you very much for being a contributor. Nothing else can be said except that you are an excellent developer. We love your research effort, detailed explanation, patience, coding style, and everything about you. We will love you even more if you find and report possible bugs in our tools and code.

**Comment by moody2times** [comment]
Thanks for approving the pull request and for your kind remarks, I am really pumped 😄. 
I will love to help more because to be honest, contributing to this repo kindled my interests in a11y. So, I desire to do more by working further on your repo to solve other accessibility issues I found in it. I have attached a png file of the a11y issues remaining. If you like, I can begin contributing to those. If I find any other bugs, I will definitely let you know. 
Thanks for the opportunity to contribute.

a11y

**Comment by mmaismma** [comment]
That's very nice of you! Once you accept the invitation to Hermit-Tools, you can create a new branch (e.g. accessibility-concerns) to work on those issues. I would encourage you to fix one issue per commit.

**Comment by moody2times** [comment]
Thank you very much for the invite, I really appreciate it. I understand your advise, I read it in the contributing guide that resolving issues should be atomic. That is why I did not do all of them in one go. And thanks for fixing the bug in my code, I notice that any key was triggering the hidden input and I came to check and saw it was resolved.

I have a favour to ask though. I found your repo while participating in hacktoberfest. However, your repo is non-participating. So then, can you use the label "hacktoberfest-accepted" for the PRs I will make from now on so that it will be two birds, one stone for me? Please  🙏
________________________________

**Comment by mmaismma** [comment]
We were and are aware of *Hacktober Fest 2020*. But we missed adding the topic to our repo. Thanks for reminding us, we have added *`hacktoberfest`* as our repo's topic! That means your PRs should be eligible for the fest. Good luck with Hacktober🤗!

**Pull request merged**
